### ISSUE TITLE
Presentation of feedback

### ISSUE THREAD

**Issue by bohungi** [rw-moore/SciLO#130] opened 2022-03-10 17:59 UTC
Feedback that's provided in a decision node is currently just presented as a list at the bottom of a question. Such feedback can be much more helpful if it is presented in direct association with the appropriate answer field (provided, there is one such).

Need to think about how to best accomplish this.

**Comment by corlick98** [comment] 2022-03-11 07:21
duplicate of #124 
closing to try to keep all conversations in 1 place

**Closed as completed by corlick98** 2022-03-11 07:21 UTC
